### ISSUE TITLE
Change needed for recall behavior

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/alma-notices#175]
1. For now, disable the Shortened Due Date Letter.
2. The messages in the 'Labels' tab of the Loan Status Notice letter need to be changed. Here is what they are now:

message (the message for when the due date is changed without a recall):
`The library has changed the due date of your borrowed item. See details for change in due date`

cancel_recall_date_change (for when a due date is reverted due to a recall being cancelled):
`The recall that has been placed on your borrowed item has been cancelled, and the original due date has been restored. See details for change in due date`

cancel_recall_renew (for when a recall is cancelled and the loan to the original patron is renewed):
`The recall that has been placed on your borrowed item has been cancelled. The loan has been renewed. See details for change in due date`

cancel_recall_no_date_change (for when a recall is cancelled but you don't change the shortened due date):
`The recall that has been placed on your borrowed item has been cancelled. There is no change in its due date`

recall_and_date_change (for when a recall shortens a due date):
`Your borrowed item has been recalled. See details for change in due date`

recall_and_no_date_change (for when a recall does not modify the due date, likely not used):
`Your borrowed item has been recalled. There is no change in its due date`

Joan and Angie will have to work out the language for each of these scenarios.

3. The template for the Loan Status Notice needs to revert to its previous functionality that conditionally applied the above messages based on the `notification_data/message` field of the XML. All other current formatting should remain the same.

**Comment by regineheberlein** [comment]
Hi
 
Here are the messages which need to be associated with the Loan Status Notice letter. Mark opened a ticket (#175) for updating the behavior so that recall messages do not continue to go out to patrons with extended due dates. It’s very confusing and it’s a customer service issue at this point. I’d appreciate it if this could be updated soon.
 
The subject of the notice letter should be “Recall or other due date change”.
 
I marked several NA (#3,4,6)  because we don’t intend to use those. We do want to instead use #2 when a recall is cancelled. I assume that can be set up in our configuration if it isn’t already.
 
1.message (the message for when the due date is changed without a recall):
The library has changed the due date of your borrowed item. See details below for the new due date.
2.cancel_recall_date_change (for when a due date is reverted due to a recall being cancelled):
The recall that was placed on your borrowed item has been cancelled, and the original due date has been restored. See details below for the due date.
3.NA: cancel_recall_renew (for when a recall is cancelled and the loan to the original patron is renewed):
The recall that was placed on your borrowed item has been cancelled. The loan has been renewed. See details below for the due date.
4.NA: cancel_recall_no_date_change (for when a recall is cancelled but you don't change the shortened due date):
The recall that was placed on your borrowed item has been cancelled. There is no change in its due date
5.recall_and_date_change (for when a recall shortens a due date):
The following item, currently loaned to you, has been recalled for course reserve or another borrower. Please return it by the new due date to avoid recall fines. 
6.NA: recall_and_no_date_change (for when a recall does not modify the due date, likely not used):
Your borrowed item has been recalled. There is no change in its due date.
 
Thank you,
Joan

**Comment by regineheberlein** [comment]
Hi
I did a little testing and the language looks good.  I noticed that the subject still needs to be updated.
I’ll do more testing. 
 
Thanks,
Joan

**Comment by regineheberlein** [comment]
Subject should read

“Recall or other due date change”

**Comment by regineheberlein** [comment]
done
